# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3d4f79d8d0297114504a19555b7e8d506e97d56283b71835b902104e421cb2957d453b651e16d629190dcaeab553a1b7eebe5c8b33d9d8b91f7eeef4cdeeb8d

test:
  secret_key_base: a2bda86202cd9aeb7f5a09607dc087f95a2a4a39abe70bd1ec755dd25780b9abf86af64fa15ce5a2521d52b64e7e95f64a4261bdab2a92183459dc54e72fbe3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
